#!/usr/bin/env bash
# Displays numbers in 1 to 100 format. 
# displays fizzbuzz in multiples of 3 and 5
# displays fizz if mupltiple of 3
# displays buzz if multiple of 5

while [ $(( i += 1 )) ] 
do
	( [ $((i % 15 )) -eq 0 ] && echo FizzBuzz ) ||
	( [ $((i % 3 )) -eq 0 ] && echo Fizz ) ||
	( [ $((i % 5 )) -eq 0 ] && echo Buzz ) ||
	echo $i
	sleep 1
done
