#!/usr/bin/env bash
# Displays numbers in 1 to 100 format. 
# displays fizzbuzz in multiples of 3 and 5
# displays fizz if mupltiple of 3
# displays buzz if multiple of 5
for ((i=1;i<100;i++)): 
do
	if ! ((i%15)); 
	then
		echo Fizzbuzz
	elif ! ((i%3));
	then
		echo Fizz
	elif ! ((i%5));
	then 
		echo Buzz
	else
		echo $i
	fi;
done
