#!/usr/bin/env bash
# Displaying best school 10 times but on line 9 it will display hi as well. #
count=0
while [$count -lt 1-]
do
	if [$count -lt]
	then
		echo "Hi"
	fi
	echo "Best School"
	((count++))
done
