#!/usr/bin/env bash
# script displays the content of current directory in list format only the part of the name after the first dash tho
list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
