#!/usr/bin/env bash
# script gives info about school file

if [ -e "school" ]
then
	echo "school file exisits"
	if [-s "school" ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "scho0ol is a regular file"
	fi
else 
	echo "school files doe not exist"
fi
